import type { Mood, PromptType } from "../domain/entities/prompt";
import type { DateNightStep, PlayContext } from "../domain/entities/game-session";

export interface StaticPromptTemplate {
  readonly id: string;
  readonly type: PromptType;
  readonly mood: Mood;
  readonly intensity: 1 | 2 | 3;
  readonly text: string;
  readonly followUp?: string;
  readonly playContexts?: readonly PlayContext[];
  readonly dateNightStep?: DateNightStep;
}

export const staticPromptTemplates: readonly StaticPromptTemplate[] = [
  {
    id: "truth-cozy-1-appreciation",
    type: "truth",
    mood: "cozy",
    intensity: 1,
    text: "What is one tiny thing your partner does that makes your day easier?",
    followUp: "When did you last notice it?",
  },
  {
    id: "dare-funny-1-award-speech",
    type: "dare",
    mood: "funny",
    intensity: 1,
    text: "Give your partner a wildly sincere 20-second award speech.",
    playContexts: ["meet", "e_meet"],
  },
  {
    id: "couple-question-romantic-2-ritual",
    type: "couple_question",
    mood: "romantic",
    intensity: 2,
    text: "What is a small date-night ritual you would love to repeat?",
  },
  {
    id: "this-or-that-flirty-safe-2-dance-note",
    type: "this_or_that",
    mood: "flirty_safe",
    intensity: 2,
    text: "Slow dance in the kitchen or a secret compliment note?",
  },
  {
    id: "couple-question-cozy-1-perfect-evening",
    type: "couple_question",
    mood: "cozy",
    intensity: 1,
    text: "What would make tonight feel extra easy and sweet?",
  },
  {
    id: "couple-question-funny-1-silly-team",
    type: "couple_question",
    mood: "funny",
    intensity: 1,
    text: "What silly thing would we be weirdly good at as a team?",
  },
  {
    id: "truth-cozy-1-lately-smile",
    type: "truth",
    mood: "cozy",
    intensity: 1,
    text: "What did I do recently that made you smile quietly?",
  },
  {
    id: "dare-cozy-1-compliment",
    type: "dare",
    mood: "cozy",
    intensity: 1,
    text: "Send one specific compliment your partner would not expect.",
    playContexts: ["e_meet"],
  },
  {
    id: "this-or-that-cozy-1-movie-snack",
    type: "this_or_that",
    mood: "cozy",
    intensity: 1,
    text: "Movie night with snacks or a slow walk together?",
  },
  {
    id: "this-or-that-funny-1-chaos-or-calm",
    type: "this_or_that",
    mood: "funny",
    intensity: 1,
    text: "A chaotic cooking challenge or a suspiciously serious board game?",
  },
  {
    id: "truth-romantic-2-first-soft-moment",
    type: "truth",
    mood: "romantic",
    intensity: 2,
    text: "When was a moment you felt especially close to me?",
  },
  {
    id: "this-or-that-romantic-2-note-or-voice",
    type: "this_or_that",
    mood: "romantic",
    intensity: 2,
    text: "A handwritten note or a soft voice message?",
  },
  {
    id: "dare-romantic-2-voice-note",
    type: "dare",
    mood: "romantic",
    intensity: 2,
    text: "Send a short voice note saying one thing you adore about your partner.",
    playContexts: ["e_meet"],
  },
  {
    id: "couple-question-deep-2-future-support",
    type: "couple_question",
    mood: "deep",
    intensity: 2,
    text: "What is one future version of us you want to protect?",
    followUp: "What small habit would help us get there?",
  },
  {
    id: "couple-question-flirty-safe-2-tiny-spark",
    type: "couple_question",
    mood: "flirty_safe",
    intensity: 2,
    text: "What tiny moment between us still gives you a little spark?",
  },
  {
    id: "after-dark-romantic-1-soft-boundary",
    type: "after_dark",
    mood: "romantic",
    intensity: 1,
    text: "What kind of closeness feels especially comforting to you tonight?",
    followUp: "What would make it feel even easier to enjoy?",
  },
  {
    id: "after-dark-flirty-safe-1-attention",
    type: "after_dark",
    mood: "flirty_safe",
    intensity: 1,
    text: "What is one small look, phrase, or gesture from me that gets your attention?",
  },
  {
    id: "after-dark-romantic-2-slow-moment",
    type: "after_dark",
    mood: "romantic",
    intensity: 2,
    text: "Describe a slow, cozy moment you would like us to create together.",
    followUp: "What detail would make it feel more like us?",
  },
  {
    id: "after-dark-flirty-safe-2-private-compliment",
    type: "after_dark",
    mood: "flirty_safe",
    intensity: 2,
    text: "What private compliment would you like to hear more often?",
  },
  {
    id: "after-dark-deep-3-wanted",
    type: "after_dark",
    mood: "deep",
    intensity: 3,
    text: "When do you feel most wanted by me in a way that still feels safe and loved?",
    followUp: "What should I remember about that?",
  },
  {
    id: "couple-question-deep-3-understood",
    type: "couple_question",
    mood: "deep",
    intensity: 3,
    text: "Where do you most want to feel understood by me lately?",
    followUp: "What would help you feel that this week?",
  },
  {
    id: "truth-flirty-safe-3-favorite-look",
    type: "truth",
    mood: "flirty_safe",
    intensity: 3,
    text: "What is one look or gesture from me that still gets your attention?",
  },
  {
    id: "this-or-that-deep-2-talk-or-silence",
    type: "this_or_that",
    mood: "deep",
    intensity: 2,
    text: "A long honest talk or quiet comfort side by side?",
  },
  {
    id: "this-or-that-flirty-safe-3-secret-or-surprise",
    type: "this_or_that",
    mood: "flirty_safe",
    intensity: 3,
    text: "A secret compliment or a surprise date clue?",
  },
  {
    id: "dare-flirty-safe-3-date-invite",
    type: "dare",
    mood: "flirty_safe",
    intensity: 3,
    text: "Write your partner a playful two-line invite for your next date.",
    playContexts: ["meet", "e_meet"],
  },
  {
    id: "dare-cozy-1-eye-contact",
    type: "dare",
    mood: "cozy",
    intensity: 1,
    text: "Give your partner a sincere 10-second compliment while making eye contact.",
    playContexts: ["meet"],
  },
  {
    id: "dare-romantic-2-handwritten-note",
    type: "dare",
    mood: "romantic",
    intensity: 2,
    text: "Write a tiny note and hand it to your partner without explaining it first.",
    playContexts: ["meet"],
  },
  {
    id: "date-night-warm-up-cozy-1-arrive",
    type: "couple_question",
    mood: "cozy",
    intensity: 1,
    dateNightStep: "warm_up",
    text: "What would help you feel fully here with me tonight?",
  },
  {
    id: "date-night-warm-up-romantic-1-soft-start",
    type: "couple_question",
    mood: "romantic",
    intensity: 1,
    dateNightStep: "warm_up",
    text: "What is one soft thing from today you want me to know?",
  },
  {
    id: "date-night-warm-up-funny-1-tiny-chaos",
    type: "couple_question",
    mood: "funny",
    intensity: 1,
    dateNightStep: "warm_up",
    text: "What tiny chaos from today deserves a dramatic retelling?",
  },
  {
    id: "date-night-warm-up-deep-2-current-weather",
    type: "couple_question",
    mood: "deep",
    intensity: 2,
    dateNightStep: "warm_up",
    text: "If your mood had weather right now, what would it be?",
    followUp: "What would make it easier to be with?",
  },
  {
    id: "date-night-warm-up-flirty-safe-2-notice",
    type: "couple_question",
    mood: "flirty_safe",
    intensity: 2,
    dateNightStep: "warm_up",
    text: "What is one thing you noticed about me today, even if it was tiny?",
  },
  {
    id: "date-night-play-cozy-1-comfort-choice",
    type: "couple_question",
    mood: "cozy",
    intensity: 1,
    dateNightStep: "play",
    text: "Pick our cozy setting: blanket fort, candle table, or late-night snack run?",
  },
  {
    id: "date-night-play-funny-1-team-name",
    type: "couple_question",
    mood: "funny",
    intensity: 1,
    dateNightStep: "play",
    text: "If we had a ridiculous team name tonight, what would it be?",
  },
  {
    id: "date-night-play-romantic-2-mini-date",
    type: "couple_question",
    mood: "romantic",
    intensity: 2,
    dateNightStep: "play",
    text: "Choose a tiny date for us: slow song, shared dessert, or one sweet photo?",
  },
  {
    id: "date-night-play-deep-2-easy-yes",
    type: "couple_question",
    mood: "deep",
    intensity: 2,
    dateNightStep: "play",
    text: "What is an easy yes for you when we spend time together?",
  },
  {
    id: "date-night-play-flirty-safe-2-spark-choice",
    type: "couple_question",
    mood: "flirty_safe",
    intensity: 2,
    dateNightStep: "play",
    text: "Which sounds more like us tonight: playful teasing or soft attention?",
  },
  {
    id: "date-night-closer-cozy-1-small-care",
    type: "couple_question",
    mood: "cozy",
    intensity: 1,
    dateNightStep: "closer",
    text: "What is one small kind of care that has meant a lot lately?",
  },
  {
    id: "date-night-closer-romantic-2-close-moment",
    type: "couple_question",
    mood: "romantic",
    intensity: 2,
    dateNightStep: "closer",
    text: "What recent moment made you feel close to me?",
    followUp: "What made that moment land?",
  },
  {
    id: "date-night-closer-funny-2-silly-truth",
    type: "couple_question",
    mood: "funny",
    intensity: 2,
    dateNightStep: "closer",
    text: "What silly thing about us feels weirdly meaningful?",
  },
  {
    id: "date-night-closer-deep-3-understood",
    type: "couple_question",
    mood: "deep",
    intensity: 3,
    dateNightStep: "closer",
    text: "Where would you like to feel a little more understood by me?",
    followUp: "What would be a gentle first step?",
  },
  {
    id: "date-night-closer-flirty-safe-3-wanted",
    type: "couple_question",
    mood: "flirty_safe",
    intensity: 3,
    dateNightStep: "closer",
    text: "What makes you feel wanted by me in a way that still feels easy and safe?",
  },
  {
    id: "date-night-appreciation-cozy-1-thank-you",
    type: "couple_question",
    mood: "cozy",
    intensity: 1,
    dateNightStep: "appreciation",
    text: "What is one ordinary thing I do that deserves a real thank you?",
  },
  {
    id: "date-night-appreciation-romantic-2-loved-detail",
    type: "couple_question",
    mood: "romantic",
    intensity: 2,
    dateNightStep: "appreciation",
    text: "What detail about the way I love you do you want me to keep doing?",
  },
  {
    id: "date-night-appreciation-funny-1-favorite-weird",
    type: "couple_question",
    mood: "funny",
    intensity: 1,
    dateNightStep: "appreciation",
    text: "What is your favorite weird little thing about us?",
  },
  {
    id: "date-night-appreciation-deep-2-seen",
    type: "couple_question",
    mood: "deep",
    intensity: 2,
    dateNightStep: "appreciation",
    text: "When have I made you feel seen lately?",
    followUp: "What helped you receive it?",
  },
  {
    id: "date-night-appreciation-flirty-safe-2-attention",
    type: "couple_question",
    mood: "flirty_safe",
    intensity: 2,
    dateNightStep: "appreciation",
    text: "What kind of attention from me makes you quietly smile?",
  },
  {
    id: "date-night-closing-cozy-1-carry",
    type: "couple_question",
    mood: "cozy",
    intensity: 1,
    dateNightStep: "closing",
    text: "What is one soft thing from tonight you want to carry with you?",
  },
  {
    id: "date-night-closing-romantic-2-tiny-plan",
    type: "couple_question",
    mood: "romantic",
    intensity: 2,
    dateNightStep: "closing",
    text: "What tiny plan should we make before this feeling fades?",
  },
  {
    id: "date-night-closing-funny-1-sign-off",
    type: "couple_question",
    mood: "funny",
    intensity: 1,
    dateNightStep: "closing",
    text: "What should tonight's official silly sign-off be?",
  },
  {
    id: "date-night-closing-deep-2-tomorrow",
    type: "couple_question",
    mood: "deep",
    intensity: 2,
    dateNightStep: "closing",
    text: "What is one thing we can do tomorrow that would feel like care?",
  },
  {
    id: "date-night-closing-flirty-safe-3-next-spark",
    type: "couple_question",
    mood: "flirty_safe",
    intensity: 3,
    dateNightStep: "closing",
    text: "What little spark should we save for our next date night?",
  },
];
