import { sql } from "drizzle-orm";
import {
  doublePrecision,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

export const gameSessions = pgTable("game_sessions", {
  id: uuid("id").primaryKey().default(sql`uuidv7()`),
  guildId: text("guild_id").notNull(),
  channelId: text("channel_id").notNull(),
  hostUserId: text("host_user_id").notNull(),
  playerIds: jsonb("player_ids").$type<string[]>().notNull(),
  mode: text("mode").notNull(),
  mood: text("mood").notNull(),
  intensity: integer("intensity").notNull(),
  recentPromptIds: jsonb("recent_prompt_ids").$type<string[]>().notNull(),
  recentPromptTexts: jsonb("recent_prompt_texts").$type<string[]>().notNull().default([]),
  promptQueue: jsonb("prompt_queue").$type<unknown[]>().notNull().default([]),
  promptQueueType: text("prompt_queue_type"),
  currentPrompt: jsonb("current_prompt").$type<unknown>(),
  playContext: text("play_context").notNull().default("e_meet"),
  choiceVotes: jsonb("choice_votes").$type<unknown[]>().notNull().default([]),
  currentTurnIndex: integer("current_turn_index").notNull().default(0),
  phase: text("phase").notNull().default("prompt_revealed"),
  status: text("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  endedAt: timestamp("ended_at", { withTimezone: true }),
});

export const aiPromptGenerations = pgTable("ai_prompt_generations", {
  id: uuid("id").primaryKey().default(sql`uuidv7()`),
  provider: text("provider").notNull(),
  baseUrl: text("base_url").notNull(),
  model: text("model").notNull(),
  promptType: text("prompt_type").notNull(),
  mood: text("mood").notNull(),
  intensity: integer("intensity").notNull(),
  playContext: text("play_context"),
  requestedCount: integer("requested_count").notNull(),
  attempt: integer("attempt").notNull(),
  maxTokens: integer("max_tokens").notNull(),
  temperature: doublePrecision("temperature").notNull(),
  validationStatus: text("validation_status").notNull(),
  validationErrors: jsonb("validation_errors").$type<string[]>().notNull().default([]),
  questionCount: integer("question_count").notNull(),
  content: text("content").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});
